### ISSUE TITLE
xtalopt CLI can't exit automatically after it completes all the defined searches

### ISSUE THREAD

**Issue by mhwang2000** [xtalopt/XtalOpt#25]
When I run xtalop CLI in a bash script:
xtalopt --cli  --input-file xtalopt.in

it seems it never ends even if all the searches defined in the input file have been completed. From the user guide, "If one wishes to end the CLI run at any time, they just need to use "ctrl-C" or whatever their process interruption
command is." Should I manually terminate xtalopt CLI after all searches are finished? It would be extremely useful if xtalopt can exit normally after all searches are finished. I am using  XtalOpt r12.0.

**Comment by lilithean** [comment]
Hi,

Yes xtalopt CLI should be manually shut down. The reason we keep XtalOpt running is you can let it continue by changing the total number of structures in the run-time-options file. 

Best

**Comment by mikewang2000** [comment]
Hi,

It would be great if xtalopt developers could add the functionality that allows xtalopt CLI to exit automatically after it completes all defined searches. It could be triggered with the command line argument. For example,
xtalopt --cli --input-file xtalopt.in --autoexit

Users can still keep xtalopt running by default without such command line argument.  Such functionality would not affect all the existing features, but gives users more choice. BTW, such functionality is extremely helpful for us in the University of Liverpool.  In our bash scripts, we expect xtalop CLI to exit automatically after completing all defined searches, then we could proceed further  (more other Linux commands to run).

Many thanks

**Comment by ezurek** [comment]
Dear Manhui

thank you for your useful suggestion. We will take it into consideration 
in our next version release.

Regards
Eva

---------------------------------------------------
  Dr. Eva Zurek

  Professor, Theoretical Chemistry
  Department of Chemistry
  University at Buffalo
  State University of New York
  777 Natural Sciences Complex
  Buffalo, NY 14260-3000

  EMail : ***@***.***
  Phone : (+01)-716-645-4332
  FAX   : (+01)-716-645-6963
  WWW   : http://www.acsu.buffalo.edu/~ezurek/
---------------------------------------------------

**Comment by mikewang2000** [comment]
Great, I am looking forward to the next release with such functionality. 

Many thanks

**Comment by mikewang2000** [comment]
Is there any progress about new functionality? We desperately need such functionality. 

Many thanks

**Comment by lilithean** [comment]
Dear Manhui,

Sorry we haven't implemented this function yet. Could you describe the problem you are facing without this function?

Thanks,
Xiaoyu

**Comment by mikewang2000** [comment]
Hi Xiaoyu,

As we know, xtalopt can be run locally (both xtalopt and optimizations are run on the same machine/node) or remotely (xtalopt is run on head node or a desktop, and all optimizations are run on compute nodes of a cluster). For our cases, xtalopt may carry out thousands of searches (optimizations) to find a global minima, and each optimization may take just a couple of minutes. Thus, running xtalopt in remote mode is not a good option as we need to submit thousands of optimization jobs to the queuing system, wait, and collect results for just one instance. Therefore, we choose the local mode to run xtalopt. We just submit one job to the queuing system. Once the job gets running, both xtalopt and optimizations are carried out on the same compute node. This works well, but the trouble is that xtalopt won't automatically exit after it completes all defined optimizations.  Thus, the compute node is almost idle, but the job is still occupying the compute node in the queue as running state. The computer resource has been wasted in such way.  For example, if we request 5-days for the job and it takes four days to complete all optimizations, then  one compute node is wasted for 1 day ( that is 40x24=960 cpu-hours). We have many xtalopt jobs, so the wasting could be enormous. We can't estimate the exact running time for every instance. 

Currently, we could manually check if the compute node is idle or not, and then manually kill the job. We have also found a workaround to terminate the xtalopt semi-automatically. The idea is to run xtalopt in the background,  meanwhile check if the file results.txt contains the string “In progress” or results.txt has been modified in the last N minutes. If results.txt has not met any of two conditions, then xtalopt is deemed to complete all the defined searches, and the job can exit. However, neither of these approaches is perfect.  Implementing automatic exit function in xtalopt could effectively avoid wasting the computer resource. 

Thanks,
Manhui

**Comment by lilithean** [comment]
Dear Manhui,

Thanks for your kind reply and patient description of the problem.

We didn't set an automatic termination to XtalOpt b/c we stop when the GA
search is "converged", say, no structure with lower enthalpy can be found
within this search.
This is a soft criterion which is hard to be programmed into the code. The
users have to decide if the search is converged, therefore they could
continue the search (by increasing the total number of structures) or stop
it (by canceling the job from the queue).
Under this consideration auto-termination is probably not a good idea.

However for your case I see the auto-termination is indeed an important
function to be implemented.
We could put a checkbox for this.

Thanks again for your feedback and suggestions!

Best,
Xiaoyu

**Comment by mikewang2000** [comment]
Hi Xiaoyu,

I am looking forward to seeing the new release with such function.

Thanks,
Manhui

**Comment by ezurek** [comment]
Dear Manhui

I am sorry it took so long to get back to you. My student Cooper is 
working on this problem, and he is just finishing it up. Perhaps you can 
discuss with him to make sure that he modifies the program in a way that 
fits your needs the best.

Best
Eva

**Comment by mhwang2000** [comment]
Hi Eva,

I would be very happy to test the new version/patch and provide feedback once it is available. Please let me know if you need further information at the moment.

Thanks,
Manhui

**Comment by hajinazar** [comment]
Dear Manhui,

The new release of XtalOpt (version 13) has the functionality that you've mentioned here. You can run XtalOpt as usual, with the "softExit=true" flag in the input file. Then, the code will quit after generating the maximum number of structures set in the input file.

Best,
Samad
